services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
    volumes:
      - /home/rodhfr/Docker/bazarr/config/:/config
      - /media/movies:/movies #optional
      - /media/tv:/tv #optional
    ports:
      - "127.0.0.1:6767:6767"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
    volumes:
      - /home/rodhfr/Docker/radarr/config/:/config
      - /media/movies:/movies #optional
      - /media/tv:/tv #optional
      - /media/downloads/:/downloads
    ports:
      - "127.0.0.1:7878:7878"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/recife
    volumes:
      - /home/rodhfr/Docker/prowlarr/config/:/config
    ports:
      - "127.0.0.1:9696:9696"
    restart: unless-stopped
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
      - WEBUI_PORT=8079
      - TORRENTING_PORT=6881
    volumes:
      - /home/rodhfr/Docker/qbittorrent/config/:/config
      - /media/downloads/:/downloads
    ports:
      - "127.0.0.1:8079:8079"
      - "127.0.0.1:6881:6881"
      - "127.0.0.1:6881:6881/udp"
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /home/rodhfr/Docker/jackett/config/:/config
      - /media/downloads/jackett-blackhole/:/downloads
    ports:
      - "127.0.0.1:9117:9117"
    restart: unless-stopped
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Recife
    ports:
      - "127.0.0.1:8191:8191"
    restart: unless-stopped 
  whisper-asr-service:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Recife
    volumes:
      - /home/rodhfr/Docker/sonarr/config/:/config
      - /media/tv:/tv 
      - /media/downloads/:/downloads
    ports:
      - "127.0.0.1:8989:8989"
    restart: unless-stopped


