services:
#  filegator:
#    image: filegator/filegator
#    container_name: filegator
 #   ports:
#      - "127.0.0.1:7777:8080"
#    restart: unless-stopped

  miniserve:
    image: docker.io/svenstaro/miniserve
    ports:
      - "127.0.0.1:7777:8080"
    volumes:
      - /home/rodhfr/Miniserve:/tmp
      #command: /tmp    # Serve the /tmp directory
    command: -q -u -U -z -S date --title Miniserve --auth user:password /tmp
    restart: unless-stopped




