services:
    microbin:
        container_name: microbin
        image: danielszabo99/microbin
        ports:
          - '192.168.1.100:5980:8080'
        volumes:
            - '/home/rodhfr/Docker/microbin/:/app/pasta_data'
        command: --editable --highlightsyntax --private --wide
        restart: unless-stopped
