services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: host

    ports:
      - '80:80'
      - '127.0.0.1:81:81'
      - '443:443'
    volumes:
      - /home/rodhfr/Docker/nginx-proxy-manager/data:/data
      - /home/rodhfr/Docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
